config/routes.rb
Urdating::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "sms/index"

  resources :profile
  match 'home/phone' => 'home#phone', :as => 'profile_phone'
  match '/phone_update' => 'home#phone_update', :via => [:put]
  match '/old_update' => 'profile#old_update', :via => [:put]

  resources :authentications

  get "home/index"
  match '/about' => 'home#about'
  match '/terms' => 'home#terms'
  match '/privacy' => 'home#privacy'

  get "home/about"
  get "home/how"

  get "home/contact"
  get "home/confirmation"
  
  match  '/updating' => 'profile#updating'

  
  match "/send_confirmation" => 'home#send_confirmation'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/profile' => 'profile#index', :as => :profile
  match '/incoming' => 'sms#index'
  match '/sms' => 'sms#index', :via => [:get, :post]
  match '/twilio' => 'sms#index', :via => [:post]
  match '/phone_call' => 'sms#phone_call', :via => [:post]
  match '/old_twilio' => 'sms#old_twilio'
  

  devise_for :users, :controllers => {:registrations => 'users/registrations', :confirmations => 'users/confirmations'}
  resources :users, :only => [:index, :show]
  
  resources :user_steps
  
  root :to => "home#index"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :create, :destroy, :index, :provider, :uid, :user_id
  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = current_user.authentications if current_user
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/new
  # GET /authentications/new.json
  def new
    @authentication = Authentication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/1/edit
  def edit
    @authentication = Authentication.find(params[:id])
  end

  # POST /authentications
  # POST /authentications.json
  def create
    puts 'creating the auth'
    auth = request.env['omniauth.auth']
    puts auth
    puts 'pennnnnesss'
    puts env["omniauth.auth"]
    
    # current_user.authentications.first_or_create!(:provider => auth['provider'], :uid => auth['uid'])
    # current_user.add_authentication_values(env["omniauth.auth"])
    
    # user = User.from_omniauth(env["omniauth.auth"])
    puts 'kisthereauser'
    # user = User.from_omniauth(auth, current_user)
    if current_user
      current_user.add_authentication_values(auth)
      user = current_user
    else
      user = User.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
      sign_in user
    end
    puts 'signintheuser'
    puts user
    session[:user_id] = user.id
    puts current_user
    
    
    flash[:notice] = "Good"
    redirect_to home_how_path
    # @authentication = Authentication.new(params[:authentication])
    # 
    # respond_to do |format|
    #   if @authentication.save
    #     format.html { redirect_to @authentication, notice: 'Authentication was successfully created.' }
    #     format.json { render json: @authentication, status: :created, location: @authentication }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @authentication.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /authentications/1
  # PUT /authentications/1.json
  def update
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      if @authentication.update_attributes(params[:authentication])
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= simple_form_for(@authentication) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :provider %>
    <%= f.input :uid %>
    <%= f.input :index %>
    <%= f.input :create %>
    <%= f.input :destroy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
    <th>Index</th>
    <th>Create</th>
    <th>Destroy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authentications.each do |authentication| %>
  <tr>
    <td><%= authentication.user_id %></td>
    <td><%= authentication.provider %></td>
    <td><%= authentication.uid %></td>
    <td><%= link_to 'Show', authentication %></td>
    <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
    <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>

<p>
  <b>Index:</b>
  <%= @authentication.index %>
</p>

<p>
  <b>Create:</b>
  <%= @authentication.create %>
</p>

<p>
  <b>Destroy:</b>
  <%= @authentication.destroy %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>