config/routes.rb
Urdating::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "sms/index"

  resources :profile
  match 'home/phone' => 'home#phone', :as => 'profile_phone'
  match '/phone_update' => 'home#phone_update', :via => [:put]
  match '/old_update' => 'profile#old_update', :via => [:put]

  resources :authentications

  get "home/index"
  match '/about' => 'home#about'
  match '/terms' => 'home#terms'
  match '/privacy' => 'home#privacy'

  get "home/about"
  get "home/how"

  get "home/contact"
  get "home/confirmation"
  
  match  '/updating' => 'profile#updating'

  
  match "/send_confirmation" => 'home#send_confirmation'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/profile' => 'profile#index', :as => :profile
  match '/incoming' => 'sms#index'
  match '/sms' => 'sms#index', :via => [:get, :post]
  match '/twilio' => 'sms#index', :via => [:post]
  match '/phone_call' => 'sms#phone_call', :via => [:post]
  match '/old_twilio' => 'sms#old_twilio'
  

  devise_for :users, :controllers => {:registrations => 'users/registrations', :confirmations => 'users/confirmations'}
  resources :users, :only => [:index, :show]
  
  resources :user_steps
  
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
  
  def confirmation
    puts 'atttconfirm'
    puts params
    puts current_user
    @email = params[:email]
  end
  
  def how
    puts 'hohohhohowowow'
    puts params
    puts current_user
  end
  
  def terms
  end
  
  def privacy
  end
  
  def phone_update
    @user = current_user
    puts 'updatingtheuser'
    puts params
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to home_how_path, notice: 'Added information!!.' }
        format.json { head :no_content }
      else
        format.html { render action: "phone" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def phone
    @user = current_user
  end
  
  def send_confirmation
    puts 'sending confirmation'
    puts params
    @phone = params[:phone]
    @user = current_user
    puts current_user
        
    message = "Thanks for registering for URconnecting.com. Your confirmation code is #{@user.phone_confirm}. Enter it on that page. Save this number as URconnecting in your phone"
    
    # response = $sms.send_message({
    #   from: '16477252253',
    #     to: @phone,
    #   text: message
    # })

    params = {'src' => '13069881525', 
               'dst' => @phone, 
               'text' => message,
               'type' => 'sms',
            }
    response = $sms.send_message(params)
    
    # $sms.account.sms.messages.create(
    #   :from => '+14509000103',
    #   :to => @phone,
    #   :body => message
    # )
    
    message = "How this works: #talk = Find Partner, #next = Find New Partner, #off = Sign Out, #options = This Message"

    params = {'src' => '13069881525', 
               'dst' => @phone, 
               'text' => message,
               'type' => 'sms',
            }
    response = $sms.send_message(params)
    
    # $sms.account.sms.messages.create(
    #   :from => '+14509000103',
    #   :to => @phone,
    #   :body => message
    # )
    
    render :nothing => true
  end
  
  def updating
    puts 'updating for old user'
    puts params
    @user = User.find_by_email("me@jonovono.com")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container content">

<legend><h1>About URconnecting</h1></legend>
<p>URconnecting is like ChatRoulette for your phone. It pairs you with a random person and allows you to talk to them via SMS. The other person will never see your phone number - all texts get sent to a number which is then forwarded to the other user. So the only people that see your conversation is the person you are talking to and yourself. And no one will ever see your phone number unless you give it to them. URconnecting is for University of Regina students/staff ONLY. We think this could be more exciting than paring you with a random person anywhere, because instantly you will have something you could talk about.</p>

<p>In the future we plan to allow you to specify more precisely who you want to talk to and other cool features. But for right now it is random. If you want to see some things you think would be cool let me know! </p>

<p>We are not affiliated with the University of Regina in any way.</p>

</div>

<div class="container content">

<legend><h1>Contact URconnecting</h1></legend>
<p>URconnecting was made by a current University of Regina student whom you may know.. or you may not know. Who knows! It was just a fun project that I thought could be entertaining if enough UofR students used it. So if you have any concerns/questions/recommendations/etc you can contact me via email: <b>contact@urconnecting.com</b> or tweet me:
  
  
  <a href="https://twitter.com/intent/tweet?screen_name=URconnecting" class="twitter-mention-button" data-size="large">Tweet to @URconnecting</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script> 
</div>

app/views/home/confirmation.html.erb
<h2>An email has been sent to <%= @email %>.</h2>
<p>Check your email to confirm your account! Please click the link and follow its instructions to continue setting up your account. If you do not get any email please email me at: contact@urconnecting.com</p>

<h5>Be patient! Sometimes it takes a while to deliver to UR email accounts</h5>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/how.html.erb
<% if current_user %>
<legend><h1>Get started using URconnecting!</h1></legend>
<h4><%= link_to "Click here to add some more information to your account", profile_path %></h4>
<br />
<br />
<% end %>
<div class="span4 well">
  <h3>Current Commands</h3>
  <p>URconnecting is configured to take action for the following commands. Text the command to run it.</p>
  <dl class="dl-horizontal">
    <dt>#talk</dt>
    <dd>Start a new chat.</dd>
    <br>
    <dt>#next</dt>
    <dd>End the current chat and start a new one with a new partner.</dd>
    <br>
    <dt>#off</dt>
    <dd>Stop chatting for now.</dd>
    <br>
    <dt>#options</dt>
    <dd>List all the valid commands.</dd>
  </dl>
</div>

<div class="span7">
  <p>Good stuff! You are now set up to start texting University of Regina students. You have also received a text with instructions on how to start chatting with someone, and those instructions you can always find here. Add the number to your phone's address book as "URconnecting" so that you remember what it's for. If you don't receive a text from us, you can manually add our number to your address book and text it #play to start chatting with someone:</p>
  <h3>Save this number as URconnecting in your phone.</h3>
  <h1 class="text-center">1 (306) 988-1525</h1>
  <p>And remember, no one at the University will see your phone numbers. All texts are sent through the number above</p>
</div>

<div class='span12'>
  If you have suggestions for more features please email me
</div>

app/views/home/index.html.erb
<% if current_user %>
  <% if !current_user.good_to_go? %>
<div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Not Done Registration</h4>
  Uh uh. To complete registration, you need to add your phone number.
  <h3><%= link_to 'Click Here to Complete Registration and start texting!', user_steps_path %></h3>
</div>
  <% end %>
<% end %>
<div class='span8 offset3'>
<input type="button"
  onclick="sendRequestViaMultiFriendSelector(); return false;"
  value="Invite your Facebook Friends!"
  class='btn btn-success btn-large'
/></div>
<% if !current_user %>
  <% url = '/users/sign_up' %>
<% else %>
  <% url = '#' %>
<% end %>
<!-- <h3><%= User.all.count %> University of Regina students using URconnecting.com</h3> -->
<div class='span8 information'>
  <div id="hp_banner">
  <!-- <div id="hpURGuarentee"><a class="no" href="/urguarantee/index.html" title="UR Guarantee"></a></div> -->
  </div>
  <div class='top center-it'>
    <h2>URconnecting matches you to a random <span id='uofr'>University of Regina</span> student and lets you text them</h2>
    <h4 class='small grey'>Like ChatRoulette for SMS, nothing to download</h4>
    <h4>No one will ever see your phone number!</h4>
  </div>
  
  <div class='span8 offset3'>
  <% if !current_user %>
  <a href='/users/sign_up'><input type="button"
    value="Sign Up Now!"
    class='btn btn-info btn-large'
  /></a>
  <% end %>
  </div>
  
<!-- <div id="hpApplyNow"><a class="no" href="/apply-now/index.html" title="Apply Now"></a></div> -->
                </div>
                
                <div class="span3 iphone">
                  <img src="/assets/iphone_urconnecting.png">
                </div>
                  <head>
                    <title>Request Example</title>
                  </head>

                  <body>
                    <div id="fb-root"></div>
                    <script src="http://connect.facebook.net/en_US/all.js"></script>

                    <script>
                      FB.init({
                        appId  : '424425824260829',
                        frictionlessRequests: true
                      });

                      function sendRequestToRecipients() {
                        var user_ids = document.getElementsByName("user_ids")[0].value;
                        FB.ui({method: 'apprequests',
                          message: 'My Great Request',
                          to: user_ids
                        }, requestCallback);
                      }

                      function sendRequestViaMultiFriendSelector() {
                        FB.ui({method: 'apprequests',
                          message: 'Request friends to URconnecting.com'
                        }, requestCallback);
                      }

                      function requestCallback(response) {
                        // Handle callback here
                      }
                    </script>
                  </body>

app/views/home/phone.html.erb
<center><h1>Phone Number</h1></center>
<center><h4>Do not Worry. No one will see your phone number. All texts are sent to our phone number and we just send the message to who we have randomly selected to talk to you.</h4></center>
<br />
<br />


<div class='row'>
  <div class='span6 offset3'>
  <%= form_for @user, :url => '/phone_update' do |f| %>
    <!-- # <%= devise_error_messages! %> -->
    <%= f.hidden_field :status, :value => 'active' %>

    <%= render 'shared/error_messages' %>
    <%= f.label :phone, "Enter your mobile phone number (with area code). Do not worry, no one will ever see this." %>
    <%= f.telephone_field :phone, :placeholder => 'Example: 1306777888' %>
    
    <br />
    <a href='#' id='send-confirmation' class='btn btn-success'>Send confirmation code to cell phone</a>
    
    <br />
    <br />
    <br />
    <p>You should get a text message with a five digit code. You are to enter it in the next field so that we know we are able to successfully send messages to your phone</p>
    
    <p>If you are not seeing a text message make sure your phone number is correct (should be 10 or 11 numbers). If still not working email me.
    
    <%= f.label :user_entered_confirmation, "Enter confirmation code" %>
    <%= f.text_field :user_entered_confirmation, :placeholder => 'Five digit confirmation code', :value => '' %>

    <div><%= f.submit "Continue", class: 'btn btn-large btn-primary' %></div>
  <% end %>

  </div>
</div>

app/views/home/privacy.html.erb
<div class="container content">

        <legend><h1>Privacy Policy
      	</h1></legend>

<p>
	Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
</p>

<ul>
	<li>
		Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
	</li>
	<li>
		We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.		
	</li>
	<li>
		We will only retain personal information as long as necessary for the fulfillment of those purposes. 
	</li>
	<li>
		We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
	</li>
	<li>
		Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
	</li>
	<li>
		We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
	</li>
	<li>
		We will make readily available to customers information about our policies and practices relating to the management of personal information. 
	</li>
</ul>

<p>
	We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
</p>
</div>

app/views/home/terms.html.erb
<div class="container content">

        <legend><h1>Terms of Service</h1></legend>
<p>I needed a Terms of Service page to integrate with FB so here it is.</p>


<h2>
	Web Site Terms and Conditions of Use
</h2>

<h3>
	1. Terms
</h3>

<p>
	By accessing this web site, you are agreeing to be bound by these 
	web site Terms and Conditions of Use, all applicable laws and regulations, 
	and agree that you are responsible for compliance with any applicable local 
	laws. If you do not agree with any of these terms, you are prohibited from 
	using or accessing this site. The materials contained in this web site are 
	protected by applicable copyright and trade mark law.
</p>

<h3>
	2. Disclaimer
</h3>

<ol type="a">
	<li>
You expressly agree that use of the Site is at your sole risk and discretion. The Site and all content and other information contained on the Site is provided on an "AS IS" and "AS AVAILABLE" basis without warranty of any kind, whether express or implied. URconnecting makes no warranty that (I) the Site and content or information will be uninterrupted, timely, secure or error-free, (II) the results that may be obtained from use of this Site will be effective, accurate or reliable. The Site may include technical mistakes, inaccuracies or typographical errors. URconnecting reserves the right to change the Site content and information at any time without notice.
	</li>
</ol>

<h3>
	3. Limitation of Liability.
  
</h3>
<p>In no event shall URconnecting or its affiliates be liable for any indirect, incidental, special, puntitive damages or consequential damages of any kind, or any damages whatsoever arising out of or related to your use of the Site, the content and other information obtained therein.

Certain jurisdictions prohibit the exclusion or limitation of liability for consequential or incidental damages, thus the above limitations may not apply to you.</p>
			
<h3>
	4. Revisions and Errata
</h3>

<p>
	The materials appearing on URconnecting's web site could include technical, typographical, or photographic errors. URconnecting does not warrant that any of the materials on its web site are accurate, complete, or current. URconnecting may make changes to the materials contained on its web site at any time without notice. URconnecting does not, however, make any commitment to update the materials.
</p>

<h3>
	5. Links
</h3>

<p>
	URconnecting has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by URconnecting of the site. Use of any such linked web site is at the user's own risk.
</p>

<h3>
	6. Site Terms of Use Modifications
</h3>

<p>
	URconnecting may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
</p>

<h3>
	7. Governing Law
</h3>

<p>
	Any claim relating to URconnecting's web site shall be governed by the laws of the City of Regina, Saskatchewan without regard to its conflict of law provisions.
</p>

<p>
	General Terms and Conditions applicable to Use of a Web Site.
</p>

  </div>