config/routes.rb
Urdating::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "sms/index"

  resources :profile
  match 'home/phone' => 'home#phone', :as => 'profile_phone'
  match '/phone_update' => 'home#phone_update', :via => [:put]
  match '/old_update' => 'profile#old_update', :via => [:put]

  resources :authentications

  get "home/index"
  match '/about' => 'home#about'
  match '/terms' => 'home#terms'
  match '/privacy' => 'home#privacy'

  get "home/about"
  get "home/how"

  get "home/contact"
  get "home/confirmation"
  
  match  '/updating' => 'profile#updating'

  
  match "/send_confirmation" => 'home#send_confirmation'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/profile' => 'profile#index', :as => :profile
  match '/incoming' => 'sms#index'
  match '/sms' => 'sms#index', :via => [:get, :post]
  match '/twilio' => 'sms#index', :via => [:post]
  match '/phone_call' => 'sms#phone_call', :via => [:post]
  match '/old_twilio' => 'sms#old_twilio'
  

  devise_for :users, :controllers => {:registrations => 'users/registrations', :confirmations => 'users/confirmations'}
  resources :users, :only => [:index, :show]
  
  resources :user_steps
  
  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="6qOcCP2xJP7v-PR6StlyNrACZ3hw-xKDg9TxYCmHqsY" />
    <title>URconnecting</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
    <%= favicon_link_tag 'favicon.ico' %>    
    <meta property="og:title" content="URconnecting" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.urconnecting.com" />
    <meta property="og:image" content="http://i.imgur.com/DQuxh.png" />
    <meta property="og:site_name" content="URconnecting" />
    <meta property="fb:app_id" content="424425824260829" />
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({publisher: "ur-ad096d7b-6528-9210-2ebd-de45a82daaa5"}); </script> -->
    
    <div id="fb-root"></div>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34483022-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "URconnecting.com", '/', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '/' %></li>
              <li><%= link_to "About/Contact",    '/about' %></li>
              <li><%= link_to "How to Use", home_how_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to "Add Info", profile_path %></li>
                <li><%= link_to "Sign Out",destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", '/users/sign_in' %></li>
                <li><%= link_to "Sign up", '/users/sign_up' %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container content">
      <%= yield %>
    </div>
    <div class="footer text-center">
          <div class="container footer-border">
            <div class="pull-left">
              URconnecting.com: Not affiliated with the University of Regina
            </div>
            <div class='span5 offset1'>
              <!-- <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://tunesicles.com" data-text="oaeu" data-lang="en" data-hashtags="twbmtye">Tweet</a>
            <span class='st_sharethis_hcount' displayText='ShareThis'></span>
            <span class='st_twitter_hcount' displayText='Tweet'></span>
            <span class='st_twitterfollow_hcount' displayText='Twitter Follow' st_username='URconnecting'></span> -->
            
            <div class="fb-like" data-href="http://www.urconnecting.com" data-send="true" data-layout="button_count" data-width="450" data-show-faces="false" data-font="arial"></div>
            
            <a href="https://twitter.com/URconnecting" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @URconnecting</a>
            <a href="https://twitter.com/share" data-url='http://urconnecting.com' data-text='URconnecting matches you to a random University of Regina student and lets you text them' data-hashtags='URconnecting'
            class="twitter-share-button" data-lang="en">Tweet</a>
            </div>

            <div class="pull-right">
              <a href="/about">About/Contact</a> | 
              <!-- <a href="/terms">Terms</a> | 
              <a href="/privacy">Privacy</a> | -->
            </div>
          </div>
        </div>
        
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=424425824260829";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </body>
</html>